# Generated by Django 4.1.4 on 2023-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("contry", models.CharField(default="Belarus", max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("post_code", models.BigIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("paid", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
