# Generated by Django 4.1.4 on 2023-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="customer",
            name="post_code",
            field=models.CharField(max_length=20),
        ),
    ]
