# Generated by Django 4.1.4 on 2023-02-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bascket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('products', models.JSONField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='customer.customer')),
            ],
            options={
                'db_table': 'bascket',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('M', 'Наличные'), ('C', 'Карта')], default='M', max_length=1)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_price', models.BigIntegerField()),
                ('status', models.CharField(choices=[('P', 'В обработке'), ('A', 'Собран'), ('S', 'Отправлен')], default='P', max_length=1)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_type', models.CharField(choices=[('B', 'Белпочта'), ('E', 'Европочта'), ('S', 'СДЕК'), ('P', 'Самовывоз')], default='B', max_length=1)),
                ('bascket_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buscket', to='order.bascket')),
                ('payment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_type_id', to='order.paymenttype')),
            ],
            options={
                'db_table': 'order_',
            },
        ),
    ]
