# Generated by Django 4.1.4 on 2023-03-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
