# Generated by Django 4.1.4 on 2023-03-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_type_id",
                to="order.paymenttype",
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="order",
        ),
    ]
