# Generated by Django 4.1.4 on 2023-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_group_category_names_groups_alter_group_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.AddField(
            model_name='names',
            name='manufacturers',
            field=models.ManyToManyField(to='products.manufacturer'),
        ),
    ]
