# Generated by Django 4.1.4 on 2023-02-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_group_category_names_groups_alter_group_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_man", models.CharField(max_length=100)),
                ("groups", models.ManyToManyField(to="products.group")),
            ],
            options={
                "db_table": "manufacturer",
            },
        ),
    ]
