# Generated by Django 4.1.4 on 2023-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="groups",
        ),
        migrations.AddField(
            model_name="group",
            name="manufacturer",
            field=models.ManyToManyField(to="products.manufacturer"),
        ),
    ]
