# Generated by Django 4.1.4 on 2023-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_products_group_alter_products_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.AlterModelOptions(
            name="names",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="names",
            name="img",
            field=models.ImageField(null=True, upload_to="image/%Y/%m/%d/"),
        ),
        migrations.AlterIndexTogether(
            name="group",
            index_together={("id", "name")},
        ),
        migrations.AlterIndexTogether(
            name="manufacturer",
            index_together={("id", "name_man")},
        ),
        migrations.AlterIndexTogether(
            name="names",
            index_together={("id", "value")},
        ),
        migrations.AlterIndexTogether(
            name="products",
            index_together={("id", "product_name")},
        ),
        migrations.RemoveField(
            model_name="names",
            name="c_g",
        ),
    ]
