# Generated by Django 4.1.4 on 2023-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_group_options_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="img",
            field=models.ImageField(null=True, upload_to="image/%Y/%m/%d/"),
        ),
    ]
