# Generated by Django 4.1.4 on 2023-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_group_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="img",
            field=models.ImageField(null=True, upload_to="image/%Y/%m/%d/"),
        ),
    ]
