# Generated by Django 4.1.4 on 2023-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_manufacturer_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="model",
        ),
        migrations.AddField(
            model_name="products",
            name="img",
            field=models.ImageField(null=True, upload_to="image/product/%Y"),
        ),
    ]
