# Generated by Django 4.1.7 on 2023-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_remove_products_model_products_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="names",
            name="groups",
            field=models.ManyToManyField(blank=True, to="products.group"),
        ),
        migrations.AlterField(
            model_name="names",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="image/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="images",
            field=models.ManyToManyField(blank=True, to="products.image"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/product/%Y"
            ),
        ),
    ]
